apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-runner-apps-config
  namespace: ci
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
