apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: actions-runners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: REPO_URL
          value: "https://github.com/Random-Stuffs"
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: runner-secret
              key: GITHUB_TOKEN
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name # Usa o nome único do Pod como nome do Runner
        - name: LABELS
          value: "self-hosted,k3s-pi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
