apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:latest
          ports:
            - containerPort: 80
            - containerPort: 22
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://gitlab.homelab.local'
                gitlab_rails['time_zone'] = 'America/Sao_Paulo'
                gitlab_rails['gitlab_shell_ssh_port'] = 2222
                prometheus_monitoring['enable'] = false
                alertmanager['enable'] = false
                grafana['enable'] = false
                sidekiq['concurrency'] = 5
                puma['worker_processes'] = 2
                postgresql['shared_buffers'] = '128MB'
            - name: GITLAB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitlab-secret
                  key: GITLAB_ROOT_PASSWORD
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "300m"
            limits:
              memory: "3Gi"
              cpu: "1500m"
          volumeMounts:
            - name: gitlab-data
              mountPath: /etc/gitlab
              subPath: config
            - name: gitlab-data
              mountPath: /var/log/gitlab
              subPath: logs
            - name: gitlab-data
              mountPath: /var/opt/gitlab
              subPath: data
          readinessProbe:
            httpGet:
              path: /users/sign_in
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
      volumes:
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-data
